### ISSUE TITLE
Keycaps?

### ISSUE THREAD

**Issue by drelephant** [jcmkk3/trochilidae#10]
Not an issue, just a question.

What are the white keycaps [here](https://github.com/jcmkk3/trochilidae/raw/main/rufous/photos/rufous_front.jpg)?

**Comment by jcmkk3** [comment]
Those are [Chicago Steno](https://www.asymplex.xyz/category/chicagosteno) keycaps! They are amazing. As are the DES keycaps that you can find on many of my other boards.

**Comment by drelephant** [comment]
Thanks for the link on Chicago Steno, they look nice.
